import localFont from "next/font/local";
import { Inter , Roboto} from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navebar"; // Ensure correct spelling



// Import Google font
const inter = Inter({ subsets: ["latin"] });
const roboto = Roboto({weight :['400','500','700', '900'] ,  subsets: ["latin"] });

export const metadata = {
  title: "My Next.js App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={roboto.className}
      >
        <Navbar />
        <div>
          {children}
        </div>
        <footer className="bg-blue-500 text-white p-4">
          <h1>This is my footer</h1>
        </footer>
      </body>
    </html>
  );
}
